[package]
name = "solana-ffi"
version = "0.1.0"
authors = ["Rohit Narurkar <rohit.narurkar@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.58"
solana-sdk = "1.4.12"

[build-dependencies]
cbindgen = "= 0.10.0"
